- name: Install and configure web server
  hosts: YourHost_IP-address
  become: true

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
      register: nginx_install

    - name: Copy nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify: restart nginx

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP
      apt:
        name:
          - php-fpm
          - php-mysql
        state: present
      register: php_install

    - name: Copy index.php file
      copy:
        src: index.php
        dest: /var/www/html/
      register: index_copy

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: nginx_install.changed or index_copy.changed

    - name: restart php-fpm
      service:
        name: php8.1-fpm
        state: restarted
      when: php_install.changed or index_copy.changed
