- name: Install and configure web server
  hosts: YourHost_IP-address
  become: true

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
      register: nginx_install

    - name: Copy nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify: restart nginx

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP
      apt:
        name:
          - php-fpm
          - php-mysql
        state: present
      register: php_install

    - name: Copy index.php file
      copy:
        src: index.php
        dest: /var/www/html/
      register: index_copy

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: nginx_install.changed or index_copy.changed

    - name: restart php-fpm
      service:
        name: php8.1-fpm
        state: restarted
      when: php_install.changed or index_copy.changed
      
      
      This Ansible playbook installs and configures a web server on the host with IP address xxx.xxx.xx.x.

The playbook consists of the following tasks:

Install nginx using the apt module and register the result of the installation in the variable "nginx_install".
Copy the nginx configuration file "nginx.conf.j2" to "/etc/nginx/sites-enabled/default" using the template module and notify the "restart nginx" handler.
Update the apt cache using the apt module.
Install PHP and the required PHP modules using the apt module and register the result of the installation in the variable "php_install".
Copy the "index.php" file to "/var/www/html/" using the copy module and register the result of the copy in the variable "index_copy".
The playbook also defines two handlers:

"restart nginx" - restarts the nginx service if the nginx installation or the index.php copy was changed.
"restart php-fpm" - restarts the php-fpm service if the php installation or the index.php copy was changed.
In summary, this playbook installs and configures a web server with nginx and PHP on the specified host and restarts the services if any changes were made during the installation or configuration process.
