- name: Create superusers group and add users
  hosts: all
  roles:
    - superusers
# Run the playbook to create the
 # ansible-playbook playbooks/superusers.yml -i inventory/production
                            # Or
 # ansible-playbook playbook/superusers.yml
 
 # This playbook will run the tasks defined in tasks/main.yml under the superusers role, which creates a new sudoers file at /etc/sudoers.d/superusers with the configuration for the superusers group.

